# Generated by Django 3.1.7 on 2021-04-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name_plural': 'Quantities'},
        ),
    ]
