# Generated by Django 3.1.7 on 2021-04-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210406_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='items',
        ),
    ]
